
-- Experience Table
create table public.experience (
  id bigint generated by default as identity primary key,
  role text not null,
  company text not null,
  duration text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Education Table
create table public.education (
  id bigint generated by default as identity primary key,
  degree text not null,
  institution text not null,
  year text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add Resume URL to Profile
alter table public.profiles add column if not exists resume_url text;

-- Enable RLS for new tables
alter table public.experience enable row level security;
alter table public.education enable row level security;

-- Policies for Experience
create policy "Experience viewable by everyone." on public.experience for select using (true);
create policy "Authenticated users can modify experience." on public.experience for all using (auth.role() = 'authenticated');

-- Policies for Education
create policy "Education viewable by everyone." on public.education for select using (true);
create policy "Authenticated users can modify education." on public.education for all using (auth.role() = 'authenticated');

-- Storage for Resumes (using a new bucket 'documents')
insert into storage.buckets (id, name, public) values ('documents', 'documents', true);

create policy "Documents are publicly accessible." on storage.objects for select using ( bucket_id = 'documents' );
create policy "Authenticated users can upload documents." on storage.objects for insert with check ( bucket_id = 'documents' AND auth.role() = 'authenticated' );
create policy "Authenticated users can update documents." on storage.objects for update using ( bucket_id = 'documents' AND auth.role() = 'authenticated' );
create policy "Authenticated users can delete documents." on storage.objects for delete using ( bucket_id = 'documents' AND auth.role() = 'authenticated' );
