
-- Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text,
  bio text,
  avatar_url text
);

-- Skills Table
create table public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'AI', 'Web', 'Tools', 'Core'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech text[] not null,
  image_url text, -- We will store the full URL here
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.projects enable row level security;

-- Policies (Allow "Select" for everyone, "All" for authenticated users - simplifying for now)
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

create policy "Skills are viewable by everyone." on public.skills for select using (true);
create policy "Authenticated users can modify skills." on public.skills for all using (auth.role() = 'authenticated');

create policy "Projects are viewable by everyone." on public.projects for select using (true);
create policy "Authenticated users can modify projects." on public.projects for all using (auth.role() = 'authenticated');

-- Storage Bucket for Images
insert into storage.buckets (id, name, public) values ('images', 'images', true);

create policy "Images are publicly accessible." on storage.objects for select using ( bucket_id = 'images' );
create policy "Authenticated users can upload images." on storage.objects for insert with check ( bucket_id = 'images' AND auth.role() = 'authenticated' );
